AWSTemplateFormatVersion: 2010-09-09
Description: This template is for creating Jenkins Instance with customizable networking components(Vpc, subnets) with ansible connect
Resources:
#  EC2SecurityGroup:
#    Type: "AWS::EC2::SecurityGroup"
#    Properties:
#      GroupDescription: "Jenkins sg"
#      GroupName: "jenkinsSG"
#      VpcId: 'vpc-04f3868ee26fa1d46'
#      SecurityGroupIngress:
#        -
#          CidrIp: "0.0.0.0/0"
#          IpProtocol: "-1"
#      SecurityGroupEgress:
#        -
#          CidrIp: "0.0.0.0/0"
#          IpProtocol: "-1"
#      Tags:
#        - Key: Name
#          Value: jenkinsSG
  JenkinsInstance:
    Type: AWS::EC2::Instance
    Description: Jenkins instance in Public subnet
    Properties:
      InstanceType: t2.medium
      ImageId: ami-03f4878755434977f 
      KeyName: loyal
      SubnetId: 'subnet-09b429f50b3122f44'
      SecurityGroupIds:
        - sg-0d81929ecf32b9364 #!Ref EC2SecurityGroup
      UserData:
        Fn::Base64: |
          #!/bin/bash
          apt update -y
          apt install fontconfig openjdk-17-jre docker.io -y
          wget -O /usr/share/keyrings/jenkins-keyring.asc \
          https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
          echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \
          https://pkg.jenkins.io/debian-stable binary/ | sudo tee \
          /etc/apt/sources.list.d/jenkins.list > /dev/null
          apt-get update -y
          apt-get install jenkins -y
          systemctl start jenkins
          systemctl enable jenkins

          apt update -y
          apt install -y vim zip tar wget git net-tools curl
          #changing vim default colorscheme
          cat > /etc/vim/vimrc <<eof
          syntax enable
          colorscheme ron
          autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab
          eof
          # configuring ansible
          username="ansible"
          password="ubuntu@user"
          adduser --gecos "" --disabled-password $username
          echo "${username}:${password}" | chpasswd
          # adding visudo file
          cp /etc/sudoers /etc/sudoers_copy
          sed -i 's/^root.*ALL$/root    ALL=(ALL:ALL) ALL\nansible ALL=(ALL)     NOPASSWD: ALL/' /etc/sudoers
          # changing Password authentication
          cp /etc/ssh/sshd_config /etc/ssh/sshd_config.bak
          sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/g' /etc/ssh/sshd_config && sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
          # restart sshd service
          systemctl restart sshd
          # Adding the permissions for 'jenkins' user with jenkins
          usermod -aG docker jenkins && cp /etc/group /etc/group.bak #&& sed "s/^docker:x:[0-9]:/docker:x:[0-9]:jenkins/" /etc/group
          usermod -g docker jenkins
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o /opt/awscliv2.zip
          unzip /opt/awscliv2.zip -d /opt/
          bash /opt/aws/install
          snap install kubectl --classic
      Tags:
        - Key: Name
          Value: jen0
