AWSTemplateFormatVersion: '2010-09-09'
Description: 'To create sample template version with conditions'


Parameters: 
    EnvType:
        Description: 'Environment type'
        Default : Test
        Type: String
        AllowedValues: ['Prod', 'Test', 'Dev']
        
Mappings:
  RegionMap:
    us-east-1:
      AMI: "ami-0ff8a91507f77f867"
    us-west-1:
      AMI: "ami-0bdb828fd58c52235"
    us-west-2:
      AMI: "ami-a0cfeed8"
    eu-west-1:
      AMI: "ami-047bb4163c506cd98"
    sa-east-1:
      AMI: "ami-07b14488da8ea02a0"
    ap-southeast-1:
      AMI: "ami-08569b978cc4dfa10"
    ap-southeast-2:
      AMI: "ami-09b42976632b27e9b"
    ap-northeast-1:
      AMI: "ami-06cd52961ce9f0d85"
      
Conditions:
  CreateProdResources: !Equals [!Ref EnvType, 'prod']
  CreateDevResources: !Equals [!Ref EnvType, 'Dev']
 
Resources: 
  Ec2Instance: 
    Type: 'AWS::EC2::Instance'
    Properties:
    ImageId: !FindInMap [RegionMap, !Ref "AWS::RegionName", AMI]
    InstanceType: !If [!Ref CreateProdResources, 't1.large', !If [!Ref CreateDevResources, 'm1.large', 'm1.small']]
