AWSTemplateFormatVersion: '2010-09-09'
Description: 'EC2 with a key name:key1.pem, default vpc, subnet,security group'
#Metadata : 
Parameters: 
    KeyName:
        Description: 'Name of the key used to create an EC2'
        Type: 'AWS::EC2::KeyPair::KeyName'
        Default: 'key1.pem'
        #Description: 'This parameter is to be given on commandline'
        #Type: String    
        #Default: t2.micro
        #AllowedValues:
        #    - t2.micro
        #    - t2.small
#Rules
Mappings:
    RegionMap: 
        us-east-1:
            HVM64: ami-0ff8a91507f77f867
            HVMG2: ami-0a584ac55a7631c0c
        us-west-1:
            HVM64: ami-0bdb828fd58c52235
            HVMG2: ami-066ee5fd4a9ef77f1
        eu-west-1:
            HVM64: ami-047bb4163c506cd98
            HVMG2: ami-0a7c483d527806435
        ap-northeast-1:
            HVM64: ami-06cd52961ce9f0d85
            HVMG2: ami-053cdd503598e4a9d
        ap-southeast-1:
            HVM64: ami-08569b978cc4dfa10
            HVMG2: ami-0be9df32ae9f92309
#Conditions
#Transforms
Resources:
    EC2Instance:
        Type: AWS::EC2::Instance
        Properties:
            KeyName:
                Ref: KeyName
            ImageId: !FindInMap 
              - 'RegionMap'
              - !Ref 'AWS::Region'
              - 'HVM64'
        Tags:
            - Key: Name
              Value: Feline

Outputs:
    InstanceId:
        Description: InstanceId of the newly created EC2 instance
        Value:
            Ref: EC2Instance
